name: Run Union Arena Scraper

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 10 * * 5'  # Runs daily at 15:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install beautifulsoup4 requests pymongo google-cloud-storage

    - name: Setup GCP Credentials
      run: |
        echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-credentials.json" >> $GITHUB_ENV

    - name: Run Union Arena scraper
      env:
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }} # Mongo Service
        MONGO_USER: ${{ secrets.MONGO_USER }} # Mongo Service
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} # Mongo Service
        MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }} # Mongo Service
        C_UNIONARENA: ${{ vars.C_UNIONARENA }} # MongoDB Collection
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Github Service
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }} # Union Arena Titles Search
        OPENROUTER_MODEL: ${{ vars.OPENROUTER_MODEL }} # Union Arena Titles Search
        SMTP_HOST: ${{ vars.SMTP_HOST }} # Notification Service
        SMTP_PORT: ${{ vars.SMTP_PORT }} # Notification Service
        SMTP_USER: ${{ secrets.SMTP_USER }} # Notification Service
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }} # Notification Service
      run: |
        python scrapers/unionarena/uacheckscrape.py